### ISSUE TITLE
How to make the radio button smaller than the text?

### ISSUE THREAD

**Issue by hagile** [DavydLiu/DLRadioButton#2]
Currently If I tried changing its button width and buttonSideLength its corner radius is out of the sky! Its not proper at all. Any help?

**Comment by DavydLiu** [comment]
Hi hagile,

Thanks for posting this issue. The reason for "abnormal corner radius" is because setting buttonSideLength without changing circleRadius, circleStrokeWidth, indicatorRadius accordingly.

Try this combination: buttonSideLength = 12; circleRadius = 3.0; circleStrokeWidth = 1.0; indicatorRadius = 1.5; You should be able to create a tiny radio button :).

DLRadioButton was designed to be highly flexible, feel free to play around with it. Let me know if you have further questions.

**Comment by hagile** [comment]
Ok, in that case what would be suggested height of button?

**Comment by DavydLiu** [comment]
The height of button would be entirely subjective, that been said choose what ever that looks best to you. Nonetheless, try 15 pts if you just want a quick suggestion.
