### ISSUE TITLE
Warnings on XCode 7.1

### ISSUE THREAD

**Issue by quantumarun** [DavydLiu/DLRadioButton#20]
Getting warning related to property declaration. PFA the screenshot.

![screen shot 2016-01-18 at 11 07 13 am](https://cloud.githubusercontent.com/assets/5046311/12384055/c3f842e2-bdd3-11e5-9a87-e28c90c9d6c0.png)

**Comment by DavydLiu** [comment]
I believe this is because you didn't turn Automatic Reference Counting on. `DLRadioButton` requires ARC to work properly. Please click on your project -> go to Build Settings -> search for Automatic Reference Counting -> change that from No to Yes.

I just tried to turn ARC off, and had the warnings as your screenshot.

**Comment by quantumarun** [comment]
I am using XCode 7.1 and is using ARC. I have other non-arc files which are marked with non-arc compiler flag but DLRadioButton are arc enabled.

**Comment by DavydLiu** [comment]
Not sure if there will help, can you try remove non-arc files and see if warning goes away. Also cleaning project should always be helpful.

**Comment by quantumarun** [comment]
Hi Liu,
It seems ARC was disabled in the project. Apologies for the trouble.
By the way i like your avatar especially in issues :)
