### ISSUE TITLE
I cant deselect the redio button.

### ISSUE THREAD

**Issue by aiyub007** [DavydLiu/DLRadioButton#33]
I am beginner in swift IOS I used this library is very nice  But Problem is once i select it. I cant deselect. Please help me with this problem.

I am taking two new UIButtons and I used custom class as DLRadioButton. If button group is require for that Just let me know how to get it exactly.

Thanks.

**Comment by DavydLiu** [comment]
Hi aiyub007,

Radio button isn't able to toggle was done by design. In order to deselect it, you have to group it with "other buttons". You can do so by set `otherButtons` outlet in interface builder or set 'otherButtons` property programmatically.

Also, if you do want to toggle, you can actually set `multipleSelectionEnabled` property to `YES`.

**Comment by aiyub007** [comment]
thanks.
