### ISSUE TITLE
how to make the label below the button or vertical mode?

### ISSUE THREAD

**Issue by ahikmatf** [DavydLiu/DLRadioButton#62]
or maybe inside the button?

**Comment by ndizazzo** [comment]
I was able to quickly accomplish this by nesting vertical stack views inside one horizontal one, combined with custom classes / nibs:

![screenshot 2016-11-16 10 56 21](https://cloud.githubusercontent.com/assets/728690/20354220/743b9284-abeb-11e6-9a66-81eb232dcbe5.png)
![screenshot 2016-11-16 10 56 16](https://cloud.githubusercontent.com/assets/728690/20354222/76ca4f04-abeb-11e6-931e-3ab0f8e5b8a2.png)
![screenshot 2016-11-16 10 56 12](https://cloud.githubusercontent.com/assets/728690/20354226/78fab7be-abeb-11e6-92c0-6401a361fa26.png)

Ideally, you'd be able to specify a label position, but for now this works!

**Comment by DavydLiu** [comment]
@ndizazzo Good job, man 👍

**Comment by mikeuv** [comment]
@ndizazzo  Excuse me, could you be more specific? I'm trying to duplicate your solution :) thank you.

**Comment by ndizazzo** [comment]
Sure - a picture is worth a thousand words, so I quickly whipped up an example.

![screenshot 2017-07-17 13 38 10](https://user-images.githubusercontent.com/728690/28281475-3ad98d6a-6af5-11e7-8664-ef08d86b6d91.png)

In that screen shot, that's how I nested my view hierarchy so that I could align the label with the title below the `DLRadioButton` view.

1) Make 1 stack view
2) Add 3 stack views to that master stack view
3) Add a view to each sub-stack view that will have the custom class set to `DLRadioButton`
4) Add a label to each sub-stack view

You'll need to wire up all the `IBOutlets`, then you should be able to programmatically be able to update the text, if need be.

**Comment by mikeuv** [comment]
@ndizazzo  Brilliant!!! thank you so much :D
