### ISSUE TITLE
Adding RadioGroup/RadioButtons Programmatically

### ISSUE THREAD

**Issue by troy21688** [DavydLiu/DLRadioButton#88]
I am pulling an `int` from a server and the number of radio buttons I create will depend on this variable.

Can somebody please show me how I could programmatically create a `radiogroup` with `int` number of buttons?

**Comment by rajdhakate** [comment]
you can add radio buttons using a for loop. here i wanted to add radio buttons based on an array from server.

    - (void) setRadioButtons:(DLRadioButton*)button withButtons:(NSMutableArray*)arrayOfButtons
    {

        if (button.tag == [location_typeArray count]-1)
        {
            [arrayOfButtons removeLastObject];
            button.otherButtons = arrayOfButtons;
        }
    }

and then call this method like

`[self setRadioButtons:cell.radioButton withButtons:buttonsArray];`

make sure to remove one radio button, `[arrayOfButtons removeLastObject];` because you need to set otherButtons outlet collection to one button (the one which is removed). Also check out the example provided by OP.

**Comment by rajdhakate** [comment]
make a for loop for your `int`. in this for loop make radio button objects and add it to an array. remove one last button from your array, because this button will be used to set `otherButtons`.lastly outside the loop when you have your array with radio button objects in it, add it to a button using
`button.otherButtons = arrayOfButtons;`

**Comment by DavydLiu** [comment]
@rajdhakate well explained!
